[package]
name = "example_orbtk"
version = "0.1.0"
authors = ["ogata-k <ogtkzk712@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbtk = "0.2.31"
